#Gradle
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options=-Xmx3g
org.gradle.caching=true
org.gradle.configuration-cache=true
#Kotlin
kotlin.code.style=official
kotlin.js.compiler=ir
#MPP
kotlin.mpp.enableCInteropCommonization=true
org.jetbrains.compose.experimental.jscanvas.enabled=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.native.enableKlibsCrossCompilation=true

libraryGroup=io.github.kotlinwizzard.kmptoolkit
libraryVersion=1.0.6
libraryJvm = 1.8

